/**
 * CriticalCSSInliner.js
 * ─────────────────────────────────────────────────────────────────────────────
 * SFCC Performance Toolkit — /frontend-performance
 *
 * Runtime SFCC server-side helper that:
 *   1. Reads pre-extracted critical CSS from the cartridge templates directory
 *   2. Inlines it into the page <head> as a <style> block
 *   3. Defers the main stylesheet loading via a <link rel="preload"> + JS trick
 *   4. Provides a <noscript> fallback for non-JS environments
 *
 * Usage in your main page ISML template (e.g. htmlHead.isml):
 *   <isscript>
 *     var CriticalCSSInliner = require('*/cartridge/scripts/perf/CriticalCSSInliner');
 *     var critical = CriticalCSSInliner.forPageType('pdp');
 *   </isscript>
 *
 *   ${critical.inlineStyle}
 *   ${critical.deferredLink}
 *   ${critical.noscriptFallback}
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

var File   = require('dw/io/File');
var Logger = require('dw/system/Logger').getLogger('perf', 'CriticalCSSInliner');

// ─── Configuration ────────────────────────────────────────────────────────────

/**
 * Maps logical page-type identifiers to their pre-extracted CSS filenames.
 * These files are generated by CriticalCSSExtractor.js during the build step.
 */
var PAGE_TYPE_MAP = {
    homepage: 'critical-homepage.css',
    plp      : 'critical-plp.css',
    pdp      : 'critical-pdp.css',
    cart     : 'critical-cart.css',
    checkout : 'critical-cart.css'   // Reuse cart critical CSS for checkout
};

/**
 * Path within the cartridge where extracted CSS files are stored.
 * Must match the outputDir in CriticalCSSExtractor.js.
 */
var CRITICAL_CSS_BASE = File.SEPARATOR + 'cartridge' + File.SEPARATOR
    + 'templates' + File.SEPARATOR + 'default' + File.SEPARATOR + 'critical' + File.SEPARATOR;

// ─── In-memory cache (process-level, resets on server restart) ────────────────

/** Caches file contents so each CSS file is read from disk only once. */
var _fileCache = {};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Reads a critical CSS file from the cartridge templates directory.
 * Results are cached in-process to avoid repeated file I/O.
 *
 * @param  {string} filename
 * @returns {string} CSS content or empty string if file not found
 */
function readCriticalCSS(filename) {
    if (_fileCache[filename] !== undefined) {
        return _fileCache[filename];
    }

    try {
        // Resolve path relative to the current cartridge
        var cartridgePath = require('dw/system/System').getCompatibilityMode
            ? '' : '';  // dw.io.File resolves relative to SFCC file system root

        // Use dw.io.File to locate the file within the cartridge
        var filePath = CRITICAL_CSS_BASE + filename;
        var file     = new File(filePath);

        if (!file.exists()) {
            Logger.warn('CriticalCSSInliner: file not found: {0}', filePath);
            _fileCache[filename] = '';
            return '';
        }

        var reader  = new (require('dw/io/FileReader'))(file, 'UTF-8');
        var content = reader.readAll();
        reader.close();

        _fileCache[filename] = content;
        return content;

    } catch (e) {
        Logger.error('CriticalCSSInliner: error reading {0}: {1}', filename, e.message);
        _fileCache[filename] = '';
        return '';
    }
}

/**
 * Generates a <link rel="preload"> tag that defers stylesheet loading.
 * The `onload` trick converts the preload into an applied stylesheet once
 * the browser has fetched it — without blocking rendering.
 *
 * @param  {string} cssURL   - Static URL to the full CSS bundle
 * @param  {string} [media]  - Optional media attribute (default: 'all')
 * @returns {string} HTML string
 */
function buildDeferredLink(cssURL, media) {
    var m = media || 'all';
    return [
        '<link rel="preload" href="' + cssURL + '" as="style"',
        '  onload="this.onload=null;this.rel=\'stylesheet\';this.media=\'' + m + '\'"',
        '  media="print"',
        '/>'
    ].join('\n');
}

/**
 * Generates a <noscript> fallback that loads the stylesheet normally
 * for browsers with JavaScript disabled.
 *
 * @param  {string} cssURL
 * @returns {string}
 */
function buildNoscriptFallback(cssURL) {
    return '<noscript><link rel="stylesheet" href="' + cssURL + '"></noscript>';
}

// ─── Public API ───────────────────────────────────────────────────────────────

var CriticalCSSInliner = {

    /**
     * Returns all HTML strings needed to implement critical CSS + deferred
     * stylesheet loading for a given page type.
     *
     * @param  {string} pageType  - One of: 'homepage', 'plp', 'pdp', 'cart', 'checkout'
     * @param  {string} cssURL    - Full URL to the main stylesheet (for deferred load)
     * @param  {Object} [opts]
     * @param  {boolean} [opts.skipInline]  - Skip inline critical CSS (e.g. already cached)
     * @returns {{
     *   inlineStyle      : string,   // <style>...critical css...</style>
     *   deferredLink     : string,   // <link rel="preload" ...>
     *   noscriptFallback : string,   // <noscript><link ...></noscript>
     *   hasInlinedCSS    : boolean,
     *   byteSize         : number
     * }}
     */
    forPageType: function (pageType, cssURL, opts) {
        var options  = opts || {};
        var filename = PAGE_TYPE_MAP[pageType];

        var criticalCSS = '';
        var hasInlined  = false;
        var byteSize    = 0;

        if (!options.skipInline && filename) {
            criticalCSS = readCriticalCSS(filename);
            hasInlined  = criticalCSS.length > 0;
            byteSize    = criticalCSS.length;
        }

        var inlineStyle = hasInlined
            ? '<style id="critical-css" data-page="' + pageType + '">\n' + criticalCSS + '\n</style>'
            : '';

        var deferredLink     = cssURL ? buildDeferredLink(cssURL) : '';
        var noscriptFallback = cssURL ? buildNoscriptFallback(cssURL) : '';

        if (!filename) {
            Logger.warn('CriticalCSSInliner: unknown page type "{0}"', pageType);
        }

        return {
            inlineStyle     : inlineStyle,
            deferredLink    : deferredLink,
            noscriptFallback: noscriptFallback,
            hasInlinedCSS   : hasInlined,
            byteSize        : byteSize
        };
    },

    /**
     * Clears the in-process file cache.
     * Call after a new deployment to force fresh file reads.
     */
    clearCache: function () {
        _fileCache = {};
    },

    /** Expose map for testing / extension */
    PAGE_TYPE_MAP: PAGE_TYPE_MAP
};

module.exports = CriticalCSSInliner;
