/**
 * StaticAssetPipeline.js
 * ─────────────────────────────────────────────────────────────────────────────
 * SFCC Performance Toolkit — /cdn-optimization
 *
 * Manages static asset (JS, CSS, fonts, SVGs) delivery through the SFCC
 * static file CDN with:
 *
 *   1. ASSET MANIFEST       — Reads the webpack content-hash manifest to
 *                             resolve versioned filenames at runtime.
 *                             Enables immutable caching without manual cache busting.
 *
 *   2. PRELOAD LINK BUILDER — Generates <link rel="preload"> tags for the
 *                             critical JS/CSS bundle set, reducing TTFB impact.
 *
 *   3. INTEGRITY HASH       — Reads SRI hashes from the manifest and emits
 *                             `integrity` attributes on every <script> and
 *                             <link> tag for CSP compliance.
 *
 *   4. CDN URL REWRITER     — Rewrites SFCC's default static URL
 *                             (https://www.example.com/on/demandware.static/...)
 *                             to a custom CDN hostname with shorter TTL
 *                             for assets that aren't content-hashed.
 *
 *   5. ASSET BUNDLING MAP   — Maps SFCC page types to the minimum set of
 *                             JS/CSS chunks that should be preloaded,
 *                             preventing over-prefetching on simple pages.
 *
 * Usage (in a SFCC controller or decorator):
 *   var SAP = require('*/cartridge/scripts/cdn/StaticAssetPipeline');
 *   SAP.init();  // Call once at app start
 *
 *   var pdpLinks = SAP.getPreloadLinks('pdp');
 *   // → array of <link> HTML strings ready for injection into <head>
 *
 *   var jsURL = SAP.resolveURL('js/pdp');
 *   // → '/js/pdp.a3f2b9c1.js' (content-hashed)
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

var File       = require('dw/io/File');
var FileReader = require('dw/io/FileReader');
var URLUtils   = require('dw/web/URLUtils');
var Site       = require('dw/system/Site');
var Logger     = require('dw/system/Logger').getLogger('cdn', 'StaticAssetPipeline');

// ─── Configuration ────────────────────────────────────────────────────────────

var CONFIG = {
    /**
     * Path to the webpack asset manifest (relative to cartridge static root).
     * Generated by the MiniCssExtractPlugin / WebpackManifestPlugin.
     */
    manifestPath: '/cartridge/static/default/manifest.json',

    /**
     * Custom CDN hostname for static assets.
     * Set to your CDN origin or leave null to use SFCC's default CDN.
     * Example: 'https://assets.mybrand.com'
     */
    cdnHostname: Site.getCurrent().getCustomPreferenceValue('staticCDNHostname') || null,

    /**
     * SFCC's default static URL prefix that CDN rewriting replaces.
     */
    sfccStaticPrefix: '/on/demandware.static/-/Sites',

    /**
     * How long to cache the manifest file in-process before re-reading.
     * Set to a low value during development, high in production.
     */
    manifestCacheTTL: 300000   // 5 minutes (ms)
};

// ─── Asset-to-page bundle map ─────────────────────────────────────────────────

/**
 * Maps SFCC page types to the JS and CSS chunks they require.
 * Drives the preload link generation — only chunks actually needed on the
 * current page are preloaded, preventing unnecessary bandwidth usage.
 */
var PAGE_BUNDLES = {
    home: {
        js : ['js/vendors', 'js/storefront-common', 'js/home'],
        css: ['css/main']
    },
    plp: {
        js : ['js/vendors', 'js/storefront-common', 'js/plp'],
        css: ['css/main']
    },
    pdp: {
        js : ['js/vendors', 'js/storefront-common', 'js/pdp'],
        css: ['css/main']
    },
    cart: {
        js : ['js/vendors', 'js/storefront-common', 'js/cart'],
        css: ['css/main']
    },
    checkout: {
        js : ['js/vendors', 'js/storefront-common', 'js/checkout'],
        css: ['css/main']
    },
    account: {
        js : ['js/vendors', 'js/storefront-common', 'js/account'],
        css: ['css/main']
    },
    search: {
        js : ['js/vendors', 'js/storefront-common', 'js/plp'],   // Search reuses PLP bundle
        css: ['css/main']
    }
};

// ─── In-process manifest cache ────────────────────────────────────────────────

var _manifest     = null;
var _manifestTime = 0;

/**
 * Reads and returns the asset manifest.
 * Caches the parsed JSON in memory for CONFIG.manifestCacheTTL ms.
 *
 * @returns {Object|null}  Manifest map { 'js/main': { file: 'js/main.a3f2.js', integrity: '...' } }
 */
function loadManifest() {
    var now = Date.now();
    if (_manifest && (now - _manifestTime) < CONFIG.manifestCacheTTL) {
        return _manifest;
    }

    try {
        var manifestFile = new File(CONFIG.manifestPath);
        if (!manifestFile.exists()) {
            Logger.warn('StaticAssetPipeline: manifest not found at {0}', CONFIG.manifestPath);
            return null;
        }
        var reader  = new FileReader(manifestFile, 'UTF-8');
        var content = reader.readAll();
        reader.close();

        _manifest     = JSON.parse(content);
        _manifestTime = now;
        Logger.info('StaticAssetPipeline: manifest loaded ({0} entries)', Object.keys(_manifest).length);
    } catch (e) {
        Logger.error('StaticAssetPipeline: manifest read failed: {0}', e.message);
        return null;
    }

    return _manifest;
}

// ─── URL resolution ───────────────────────────────────────────────────────────

/**
 * Resolves a logical asset name (e.g. 'js/pdp') to its content-hashed
 * physical URL using the webpack manifest.
 *
 * Falls back to the unhashed filename if the manifest is unavailable.
 *
 * @param  {string} logicalName  - Logical asset name (without extension)
 * @param  {string} [ext]        - Extension override (default: inferred from name prefix)
 * @returns {string}  Full static URL
 */
function resolveURL(logicalName, ext) {
    var manifest = loadManifest();
    var extension = ext || (logicalName.startsWith('css/') ? '.css' : '.js');
    var entry     = manifest && manifest[logicalName + extension];

    var filename = entry
        ? (typeof entry === 'string' ? entry : entry.file)
        : (logicalName + extension);

    if (CONFIG.cdnHostname) {
        return CONFIG.cdnHostname + '/' + filename.replace(/^\//, '');
    }

    return URLUtils.staticURL('/' + filename.replace(/^\//, '')).toString();
}

/**
 * Returns the SRI integrity hash for an asset, if present in the manifest.
 *
 * @param  {string} logicalName
 * @param  {string} [ext]
 * @returns {string|null}
 */
function getIntegrity(logicalName, ext) {
    var manifest  = loadManifest();
    var extension = ext || (logicalName.startsWith('css/') ? '.css' : '.js');
    var entry     = manifest && manifest[logicalName + extension];

    if (entry && typeof entry === 'object' && entry.integrity) {
        return entry.integrity;
    }
    return null;
}

// ─── CDN URL rewriter ─────────────────────────────────────────────────────────

/**
 * Rewrites a SFCC default static URL to use the configured CDN hostname.
 * No-ops if cdnHostname is not configured.
 *
 * Use in ISML templates to ensure all static asset references point to the CDN:
 *   ${SAP.rewriteToCDN(URLUtils.staticURL('/css/main.css'))}
 *
 * @param  {string|dw.web.URL} sfccURL
 * @returns {string}
 */
function rewriteToCDN(sfccURL) {
    var urlStr = sfccURL ? sfccURL.toString() : '';
    if (!CONFIG.cdnHostname || !urlStr) { return urlStr; }

    // Extract the path portion after the SFCC static prefix
    var prefixIdx = urlStr.indexOf('/on/demandware.static');
    if (prefixIdx === -1) { return urlStr; }

    // Keep the path from /on/demandware.static onward but swap the hostname
    var pathFromStatic = urlStr.substring(prefixIdx);
    return CONFIG.cdnHostname + pathFromStatic;
}

// ─── Preload link builder ─────────────────────────────────────────────────────

/**
 * Generates an array of <link rel="preload"> HTML strings for the assets
 * required by a given SFCC page type.
 *
 * These links should be injected into the page <head> as early as possible —
 * they signal to the browser (and the CDN edge node) which assets to fetch
 * immediately, reducing TTFB for subsequent requests.
 *
 * @param  {string} pageType    - Key from PAGE_BUNDLES (e.g. 'pdp', 'plp')
 * @param  {Object} [opts]
 * @param  {boolean} [opts.includeCSS]  - Include CSS preloads (default: true)
 * @param  {boolean} [opts.includeJS]   - Include JS preloads (default: true)
 * @param  {boolean} [opts.useModulePreload] - Use modulepreload instead of preload for JS
 * @returns {string[]}  Array of <link> HTML strings
 */
function getPreloadLinks(pageType, opts) {
    var options   = opts || {};
    var bundles   = PAGE_BUNDLES[pageType] || PAGE_BUNDLES['plp'];
    var links     = [];
    var includeCSS = options.includeCSS !== false;
    var includeJS  = options.includeJS  !== false;
    var jsRel      = options.useModulePreload ? 'modulepreload' : 'preload';

    // CSS preloads — emit first (render-blocking, high priority)
    if (includeCSS) {
        (bundles.css || []).forEach(function (name) {
            var url       = resolveURL(name, '.css');
            var integrity = getIntegrity(name, '.css');
            var tag = '<link rel="preload" href="' + url + '" as="style"';
            if (integrity) { tag += ' integrity="' + integrity + '" crossorigin="anonymous"'; }
            tag += '>';
            links.push(tag);
        });
    }

    // JS preloads — emit after CSS
    if (includeJS) {
        (bundles.js || []).forEach(function (name, i) {
            var url       = resolveURL(name, '.js');
            var integrity = getIntegrity(name, '.js');
            // Vendors bundle is the most critical — preload eagerly
            var fetchPriority = (i === 0) ? ' fetchpriority="high"' : '';
            var tag = '<link rel="' + jsRel + '" href="' + url + '" as="script"' + fetchPriority;
            if (integrity) { tag += ' integrity="' + integrity + '" crossorigin="anonymous"'; }
            tag += '>';
            links.push(tag);
        });
    }

    return links;
}

/**
 * Generates <script> and <link rel="stylesheet"> tags with correct SRI
 * integrity attributes for all assets required by a page type.
 *
 * @param  {string} pageType
 * @returns {{ scripts: string[], stylesheets: string[] }}
 */
function getAssetTags(pageType) {
    var bundles = PAGE_BUNDLES[pageType] || PAGE_BUNDLES['plp'];

    var stylesheets = (bundles.css || []).map(function (name) {
        var url       = resolveURL(name, '.css');
        var integrity = getIntegrity(name, '.css');
        var tag = '<link rel="stylesheet" href="' + url + '"';
        if (integrity) { tag += ' integrity="' + integrity + '" crossorigin="anonymous"'; }
        tag += '>';
        return tag;
    });

    var scripts = (bundles.js || []).map(function (name) {
        var url       = resolveURL(name, '.js');
        var integrity = getIntegrity(name, '.js');
        var tag = '<script src="' + url + '" defer';
        if (integrity) { tag += ' integrity="' + integrity + '" crossorigin="anonymous"'; }
        tag += '></script>';
        return tag;
    });

    return { scripts: scripts, stylesheets: stylesheets };
}

// ─── Exports ──────────────────────────────────────────────────────────────────

module.exports = {
    init            : loadManifest,   // Call at app startup to warm manifest cache
    resolveURL      : resolveURL,
    getIntegrity    : getIntegrity,
    rewriteToCDN    : rewriteToCDN,
    getPreloadLinks : getPreloadLinks,
    getAssetTags    : getAssetTags,
    loadManifest    : loadManifest,
    PAGE_BUNDLES    : PAGE_BUNDLES,
    CONFIG          : CONFIG
};
